services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db:/db:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h 127.0.0.1 -U postgres -d marketplace']
      interval: 2s
      timeout: 3s
      retries: 15

  pgbouncer:
    image: edoburu/pgbouncer:v1.26.0-p0
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '6432:6432'
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'PGPASSWORD=pgbouncer_dev psql -h 127.0.0.1 -p 6432 -U pgbouncer -d marketplace -qAtc "SELECT 1"',
        ]
      interval: 2s
      timeout: 3s
      retries: 15

volumes:
  pgdata:
