services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_DB: marketplace
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

secrets:
  db_password:
    file: ./secrets/db_password

volumes:
  pgdata:
