import { MigrationInterface, QueryRunner } from 'typeorm';

export class StockBalanceTasks1790474341612 implements MigrationInterface {
  name = 'StockBalanceTasks1790474341612';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            CREATE TABLE "tasks" (
                "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "type" text NOT NULL,
                "payload" jsonb NOT NULL,
                "status" text NOT NULL DEFAULT 'pending',
                "processed" integer NOT NULL DEFAULT '0',
                "worker" text,
                "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                "processed_at" TIMESTAMP WITH TIME ZONE,
                CONSTRAINT "chk_tasks_status" CHECK (status IN ('pending', 'done')),
                CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id")
            )
        `);
    await queryRunner.query(`
            CREATE INDEX "idx_tasks_status_id" ON "tasks" ("status", "id")
        `);
    await queryRunner.query(`
            ALTER TABLE "products"
            ADD "stock" integer NOT NULL DEFAULT '0'
        `);
    await queryRunner.query(`
            ALTER TABLE "users"
            ADD "balance_cents" bigint NOT NULL DEFAULT '0'
        `);
    await queryRunner.query(`
            ALTER TABLE "products"
            ADD CONSTRAINT "chk_products_stock" CHECK (stock >= 0)
        `);
    await queryRunner.query(`
            ALTER TABLE "users"
            ADD CONSTRAINT "chk_users_balance_cents" CHECK (balance_cents >= 0)
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            ALTER TABLE "users" DROP CONSTRAINT "chk_users_balance_cents"
        `);
    await queryRunner.query(`
            ALTER TABLE "products" DROP CONSTRAINT "chk_products_stock"
        `);
    await queryRunner.query(`
            ALTER TABLE "users" DROP COLUMN "balance_cents"
        `);
    await queryRunner.query(`
            ALTER TABLE "products" DROP COLUMN "stock"
        `);
    await queryRunner.query(`
            DROP INDEX "idx_tasks_status_id"
        `);
    await queryRunner.query(`
            DROP TABLE "tasks"
        `);
  }
}
